### ISSUE TITLE
[SUGGESTION] Allow scan-keyword to be a list of keywords

### ISSUE THREAD

**Issue by YPCrumble** [kiliczsh/codebase-scanner#1]
Thanks for building this! 

I have a lot of keywords I'm trying to scan my code with so being able to create a list of keywords would be ideal instead of having to create a new set of config for each keyword I'm scanning.

**Comment by kiliczsh** [comment]
@YPCrumble are you comfortable with array input and a switch option between array and single inputs? That would take a lot of time for array input just to let you know

**Comment by YPCrumble** [comment]
I ended up using a few grep one liners instead of this. The dist folder had so much stuff in it including a bunch of http strings that I couldn't verify the security of the action.

**Comment by kiliczsh** [comment]
http usages are imported from @actions/core and @actions/github therefore i don't have extra info about them. I think you don't need improvement for your suggestion as you ended up with another solution, right?
